[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc_macro = { path = "./aoc_macro" }
inventory = "0.3"
color-eyre = "0.6"
reqwest = { version = "0.12", features = ["blocking"] }
itertools = "0.14"
criterion = "0.8"
